services:
  opensearch:
    image: opensearchproject/opensearch:3.4.0
    container_name: opensearch-test
    ports:
      - 9247:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
    healthcheck:
      test: curl --fail https://localhost:9200/_cat/health -ku 'admin:admin' >/dev/null || exit 1
      interval: 10s
      timeout: 30s
      retries: 3